version: '3.8'
services:
  frontend:
    image: node:18.17.1
    restart: always
    volumes:
      - ./frontend:/home/documents/front
    command: sleep infinity
    networks:
      proyect-search-countries-network:
    ports:
      - "4001:4000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tomaslvidal/nestjs:10.1.17
    restart: always
    volumes:
      - ./backend:/home/documents/server
    command: sleep infinity
    networks:
      proyect-search-countries-network:
    ports:
      - "3050:3050"

  database:
    image: mariadb:11.1.2
    restart: always
    env_file: mariadb.properties
    networks:
      proyect-search-countries-network:
    ports:
      - "3000:3306"

networks:
  proyect-search-countries-network: